FROM openjdk:8-jre-alpine

ENV API_VERSION 1.0.1

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY countries-assembly-$API_VERSION.jar /usr/src/app/countries-assembly.jar

EXPOSE 8001

CMD ["java", "-jar", "/usr/src/app/countries-assembly.jar"]