FROM openjdk:8-jre-alpine

ENV API_VERSION 1.0.1
# ENV API_VERSION 1.1.0

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY airports-assembly-$API_VERSION.jar /usr/src/app/airports-assembly.jar

EXPOSE 8002

CMD ["java", "-jar", "/usr/src/app/airports-assembly.jar"]